sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
before_install:
  - docker build -t muzili/docker3 -f Dockerfile.dev .
script:
  - docker run muzili/docker3 npm test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker3"
  env: "Docker3-env"
  bucket_name: "elasticbeanstalk-us-east-1-952439452167"
  bucket_path: "docker3"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
