# Specify a base image
FROM node:alpine

# Specify environment variable
ENV CI=true

# Specify a working directory inside container
WORKDIR /app

# Only install dependencies if there's change with package.json file 
COPY ./package.json ./
RUN npm install

# Copy all files into container
COPY ./ ./

# Default command
CMD ["npm", "run", "start"]